import pydantic
from pydantic import Field


class LegalUnitsPeriod(pydantic.BaseModel):
    dateFin: str = Field(description="Date de fin de la période de l'unité légale")
    dateDebut: str = Field(description="Date de début de la période de l'unité légale")
    etatAdministratifUniteLegale: str = Field(description="État administratif de l'unité légale")
    changementEtatAdministratifUniteLegale: bool = Field(description="Indique si l'état administratif de l'unité légale a changé")
    nomUniteLegale: str = Field(description="Nom de l'unité légale")
    changementNomUniteLegale: bool = Field(description="Indique si le nom de l'unité légale a changé")
    nomUsageUniteLegale: str = Field(description="Nom d'usage de l'unité légale")
    changementNomUsageUniteLegale: bool = Field(description="Indique si le nom d'usage de l'unité légale a changé")
    denominationUniteLegale: str = Field(description="Dénomination de l'unité légale")
    changementDenominationUniteLegale: bool = Field(description="Indique si la dénomination de l'unité légale a changé")
    denominationUsuelle1UniteLegale: str = Field(description="Dénomination usuelle 1 de l'unité légale")
    denominationUsuelle2UniteLegale: str = Field(description="Dénomination usuelle 2 de l'unité légale")
    denominationUsuelle3UniteLegale: str = Field(description="Dénomination usuelle 3 de l'unité légale")
    categorieJuridiqueUniteLegale: str = Field(description="Catégorie juridique de l'unité légale")
    changementCategorieJuridiqueUniteLegale: bool = Field(description="Indique si la catégorie juridique de l'unité légale a changé")
    activitePrincipaleUniteLegale: str = Field(description="Activité principale de l'unité légale")
    nomenclatureActivitePrincipaleUniteLegale: str = Field(description="Nomenclature de l'activité principale de l'unité légale")
    changementActivitePrincipaleUniteLegale: bool = Field(description="Indique si l'activité principale de l'unité légale a changé")
    nicSiegeUniteLegale: str = Field(description="NIC du siège de l'unité légale")
    changementNicSiegeUniteLegale: bool = Field(description="Indique si le NIC du siège de l'unité légale a changé")
    economieSocialeSolidaireUniteLegale: str = Field(description="Économie sociale et solidaire de l'unité légale")
    changementEconomieSocialeSolidaireUniteLegale: bool = Field(description="Indique si l'économie sociale et solidaire de l'unité légale a changé")
    societeMissionUniteLegale: str = Field(description="Société mission de l'unité légale")
    changementSocieteMissionUniteLegale: bool = Field(description="Indique si la société mission de l'unité légale a changé")
    caractereEmployeurUniteLegale: str = Field(description="Caractère employeur de l'unité légale")
    changementCaractereEmployeurUniteLegale: bool = Field(description="Indique si le caractère employeur de l'unité légale a changé")
    changementDenominationUsuelleUniteLegale: bool = Field(description="Indique si la dénomination usuelle de l'unité légale a changé")


class LegalUnits(pydantic.BaseModel):
    score: float = Field(description="Score de la correspondance entre la recherche et l'unité légale")
    siren: str = Field(description="SIREN de l'unité légale")
    statutDiffusionUniteLegale: str = Field(description="Statut de diffusion de l'unité légale")
    unitePurgeeUniteLegale: bool = Field(description="Indique si l'unité légale est purgée")
    dateCreationUniteLegale: str = Field(description="Date de création de l'unité légale")
    dateNaissanceUniteLegale: str = Field(description="Date de naissance de l'unité légale")
    codeCommuneNaissanceUniteLegale: str = Field(description="Code commune de naissance de l'unité légale")
    codePaysNaissanceUniteLegale: str = Field(description="Code pays de naissance de l'unité légale")
    libelleNationaliteUniteLegale: str = Field(description="Libellé nationalité de l'unité légale")
    identifiantAssociationUniteLegale: str = Field(description="Identifiant association de l'unité légale")
    trancheEffectifsUniteLegale: str = Field(description="Tranche effectifs de l'unité légale")
    anneeEffectifsUniteLegale: str = Field(description="Année effectifs de l'unité légale")
    dateDernierTraitementUniteLegale: str = Field(description="Date dernier traitement de l'unité légale")
    nombrePeriodesUniteLegale: int = Field(description="Nombre périodes de l'unité légale")
    categorieEntreprise: str = Field(description="Catégorie entreprise de l'unité légale")
    anneeCategorieEntreprise: str = Field(description="Année catégorie entreprise de l'unité légale")
    sigleUniteLegale: str = Field(description="Sigle de l'unité légale")
    sexeUniteLegale: str = Field(description="Sexe de l'unité légale")
    prenom1UniteLegale: str = Field(description="Prénom 1 de l'unité légale")
    prenom2UniteLegale: str = Field(description="Prénom 2 de l'unité légale")
    prenom3UniteLegale: str = Field(description="Prénom 3 de l'unité légale")
    prenom4UniteLegale: str = Field(description="Prénom 4 de l'unité légale")
    prenomUsuelUniteLegale: str = Field(description="Prénom usuel de l'unité légale")
    pseudonymeUniteLegale: str = Field(description="Pseudonyme de l'unité légale")
    activitePrincipaleNAF25UniteLegale: str = Field(description="Activité principale NAF 25 de l'unité légale")
